#!/usr/bin/env python3
"""Merge the 8 Smart Requirement Manager (SRM) source screens into the single-file docreview-app.html deliverable.

Usage: python3 build_merge.py
Reads the 8 source files below, base64-encodes each (UTF-8), and writes docreview-app.html
plus an identical index.html (GitHub Pages serves index.html as the site entry point —
writing both here keeps the hosted copy in sync with the deliverable automatically).
Always edit the 8 sources — never the merged files directly — then re-run this script.

Cross-screen navigation is expressed in the sources as parent.route(...) /
parent.routeUrl(...) / goRoute(...) JS calls (see dashboard-et-config.html's
goRoute() for the standalone-fallback pattern) — not <a href="X.html"> tags.
Keep new cross-screen links in that form; there is no href rewriting here.

Shared CSS: components.css holds UI components used by more than one screen
(the ui-list list field, and whatever follows it). It is inlined the same way
via "/* @include components.css */" in a screen's own <style> block. Edit that
one file to change a component everywhere it appears.

Shared JS (B5): table-engine.js holds review-table interaction behaviour used
by more than one screen (selection, Bulk Action Bar, Filter to Selection,
keyboard navigation, Column Visibility Menu). It is a plain JS file, not a
standalone screen — before encoding each source, any "/* @include
table-engine.js */" marker in that source is replaced with its contents, so
both screens run the same code without a bundler or external <script src>
(the deliverable stays a single self-contained file). Edit table-engine.js
itself to change shared behaviour on every screen that includes it.

Real RFP data: data.js (generated by import_capture.py, see its own docstring —
never hand-edited) is inlined the same way via "/* @include data.js */", used
only by revue-documentaire.html. It sets window.SRM_DATA before that screen's
own script runs, so the merged file stays file://-loadable with no fetch().
data.js is optional: if it hasn't been generated yet, the marker is replaced
with an empty string and revue-documentaire.html's buildDataFromCapture()
falls back to its synthetic buildBigData(n) seed.
"""
import base64
from pathlib import Path

SOURCES = [
    ("dash", "dashboard-et-config.html"),
    ("review", "revue-documentaire.html"),
    ("compliance", "compliance.html"),
    ("create", "creation-projet.html"),
    ("home", "accueil.html"),
    # TICKET-three-support-screens.md — Documents & versions and Q&A are their
    # own screens, not panels inside a workflow step. Casting is the third and
    # already lives as its own screen in dashboard-et-config.html.
    ("documents", "documents.html"),
    ("qa", "qa.html"),
    # SPEC-risks.md §6 — the tender's risk register, a support screen like Q&A.
    ("risks", "risks.html"),
]

INCLUDE_MARKER = "/* @include table-engine.js */"
SHARED_JS_FILE = "table-engine.js"
# Shared CSS, same mechanism as the shared JS above. COMPONENTS.md's inventory
# found ~50 distinct list/row classes across the seven screens, all the same
# idea re-implemented per screen with independently drifted values; this is
# where the shared components live so that stops happening.
CSS_INCLUDE_MARKER = "/* @include components.css */"
SHARED_CSS_FILE = "components.css"
DATA_INCLUDE_MARKER = "/* @include data.js */"
DATA_FILE = "data.js"
# The PBS/OBS/ABS keys (DEC-061): generated by build_keys.py, committed, required.
KEYS_INCLUDE_MARKER = "/* @include keys.js */"
KEYS_FILE = "keys.js"

OUTPUT = "docreview-app.html"
PAGES_OUTPUT = "index.html"  # GitHub Pages entry point — same bytes as OUTPUT

HEADER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Smart Requirement Manager — STB-2026 · Full app</title>
<link rel="icon" type="image/svg+xml" media="(prefers-color-scheme: light)" href="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIyIDIwIDg0IDQ4IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cGF0aCBkPSJNMy4wNzAzMSA0NC4yMTczQzMuMDcwMzEgMzEuMzI4NiAxMy41MTg2IDIwLjg4MDMgMjYuNDA3MyAyMC44ODAzSDYxLjE5MDVDNjEuMzEzMiAyMC44ODAzIDYxLjQxMjcgMjAuOTc5OCA2MS40MTI3IDIxLjEwMjVWNjcuMzMyMUM2MS40MTI3IDY3LjQ1NDggNjEuMzEzMiA2Ny41NTQyIDYxLjE5MDUgNjcuNTU0MkgyNi40MDczQzEzLjUxODYgNjcuNTU0MiAzLjA3MDMxIDU3LjEwNTkgMy4wNzAzMSA0NC4yMTczVjQ0LjIxNzNaIiBmaWxsPSJ1cmwoI2ZsYSkiIGZpbGwtb3BhY2l0eT0iLjU0Ii8+CjxwYXRoIGQ9Ik0xOC40MjM4IDQ0LjIxNzNDMTguNDIzOCAzMS4zMjg2IDI4Ljg3MjEgMjAuODgwMyA0MS43NjA4IDIwLjg4MDNINjMuMDg0NkM2My4xNzg5IDIwLjg4MDMgNjMuMjU1MyAyMC45NTY4IDYzLjI1NTMgMjEuMDUxVjY3LjM4MzVDNjMuMjU1MyA2Ny40Nzc4IDYzLjE3ODkgNjcuNTU0MiA2My4wODQ2IDY3LjU1NDJINDEuNzYwOEMyOC44NzIxIDY3LjU1NDIgMTguNDIzOCA1Ny4xMDU5IDE4LjQyMzggNDQuMjE3M1Y0NC4yMTczWiIgZmlsbD0idXJsKCNmbGIpIiBmaWxsLW9wYWNpdHk9Ii41NCIvPgo8cGF0aCBkPSJNMzUuMDA1NCA0NC4yMTczQzM1LjAwNTQgMzEuMzI4NiA0NS40NTM3IDIwLjg4MDMgNTguMzQyMyAyMC44ODAzSDYxLjQxM0M3NC4zMDE2IDIwLjg4MDMgODQuNzQ5OSAzMS4zMjg2IDg0Ljc0OTkgNDQuMjE3M1Y0NC4yMTczQzg0Ljc0OTkgNTcuMTA1OSA3NC4zMDE2IDY3LjU1NDIgNjEuNDEzIDY3LjU1NDJINTguMzQyM0M0NS40NTM3IDY3LjU1NDIgMzUuMDA1NCA1Ny4xMDU5IDM1LjAwNTQgNDQuMjE3M1Y0NC4yMTczWiIgZmlsbD0idXJsKCNmbGMpIiBmaWxsLW9wYWNpdHk9Ii41NCIvPgo8Y2lyY2xlIGN4PSI2MC4zMTA1IiBjeT0iNDQuMzQzMSIgcj0iMTguNTQ5NyIgZmlsbD0iI2ZmZiIvPgo8ZGVmcz4KPGxpbmVhckdyYWRpZW50IGlkPSJmbGEiIHgxPSIzLjA3IiB5MT0iNDQuMjIiIHgyPSI2MS40MSIgeTI9IjQ0LjIyIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agc3RvcC1jb2xvcj0iIzFFMzI0NiIvPjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iIzFFMzI0NiIgc3RvcC1vcGFjaXR5PSIwIi8+PC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJmbGIiIHgxPSIxOC40MiIgeTE9IjQ0LjIyIiB4Mj0iNjMuMjYiIHkyPSI0NC4yMiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIHN0b3AtY29sb3I9IiMxRTMyNDYiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiMxRTMyNDYiIHN0b3Atb3BhY2l0eT0iMCIvPjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0iZmxjIiB4MT0iMzUuMDEiIHkxPSI0NC4yMiIgeDI9Ijg0Ljc1IiB5Mj0iNDQuMjIiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjMUUzMjQ2Ii8+PHN0b3Agb2Zmc2V0PSIuMTY4IiBzdG9wLWNvbG9yPSIjMUUzMjQ2Ii8+PC9saW5lYXJHcmFkaWVudD4KPC9kZWZzPgo8L3N2Zz4=">
<link rel="icon" type="image/svg+xml" media="(prefers-color-scheme: dark)" href="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIyIDIwIDg0IDQ4IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgo8cGF0aCBkPSJNMy4wNzAzMSA0NC4yMTczQzMuMDcwMzEgMzEuMzI4NiAxMy41MTg2IDIwLjg4MDMgMjYuNDA3MyAyMC44ODAzSDYxLjE5MDVDNjEuMzEzMiAyMC44ODAzIDYxLjQxMjcgMjAuOTc5OCA2MS40MTI3IDIxLjEwMjVWNjcuMzMyMUM2MS40MTI3IDY3LjQ1NDggNjEuMzEzMiA2Ny41NTQyIDYxLjE5MDUgNjcuNTU0MkgyNi40MDczQzEzLjUxODYgNjcuNTU0MiAzLjA3MDMxIDU3LjEwNTkgMy4wNzAzMSA0NC4yMTczVjQ0LjIxNzNaIiBmaWxsPSJ1cmwoI2ZkYSkiIGZpbGwtb3BhY2l0eT0iLjU0Ii8+CjxwYXRoIGQ9Ik0xOC40MjM4IDQ0LjIxNzNDMTguNDIzOCAzMS4zMjg2IDI4Ljg3MjEgMjAuODgwMyA0MS43NjA4IDIwLjg4MDNINjMuMDg0NkM2My4xNzg5IDIwLjg4MDMgNjMuMjU1MyAyMC45NTY4IDYzLjI1NTMgMjEuMDUxVjY3LjM4MzVDNjMuMjU1MyA2Ny40Nzc4IDYzLjE3ODkgNjcuNTU0MiA2My4wODQ2IDY3LjU1NDJINDEuNzYwOEMyOC44NzIxIDY3LjU1NDIgMTguNDIzOCA1Ny4xMDU5IDE4LjQyMzggNDQuMjE3M1Y0NC4yMTczWiIgZmlsbD0idXJsKCNmZGIpIiBmaWxsLW9wYWNpdHk9Ii41NCIvPgo8cGF0aCBkPSJNMzUuMDA1NCA0NC4yMTczQzM1LjAwNTQgMzEuMzI4NiA0NS40NTM3IDIwLjg4MDMgNTguMzQyMyAyMC44ODAzSDYxLjQxM0M3NC4zMDE2IDIwLjg4MDMgODQuNzQ5OSAzMS4zMjg2IDg0Ljc0OTkgNDQuMjE3M1Y0NC4yMTczQzg0Ljc0OTkgNTcuMTA1OSA3NC4zMDE2IDY3LjU1NDIgNjEuNDEzIDY3LjU1NDJINTguMzQyM0M0NS40NTM3IDY3LjU1NDIgMzUuMDA1NCA1Ny4xMDU5IDM1LjAwNTQgNDQuMjE3M1Y0NC4yMTczWiIgZmlsbD0idXJsKCNmZGMpIiBmaWxsLW9wYWNpdHk9Ii41NCIvPgo8Y2lyY2xlIGN4PSI2MC4zMTA1IiBjeT0iNDQuMzQzMSIgcj0iMTguNTQ5NyIgZmlsbD0iI2ZmZiIvPgo8ZGVmcz4KPGxpbmVhckdyYWRpZW50IGlkPSJmZGEiIHgxPSIzLjA3IiB5MT0iNDQuMjIiIHgyPSI2MS40MSIgeTI9IjQ0LjIyIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSI+PHN0b3Agc3RvcC1jb2xvcj0iI2ZmZiIvPjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iI2ZmZiIgc3RvcC1vcGFjaXR5PSIwIi8+PC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJmZGIiIHgxPSIxOC40MiIgeTE9IjQ0LjIyIiB4Mj0iNjMuMjYiIHkyPSI0NC4yMiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIHN0b3AtY29sb3I9IiNmZmYiLz48c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9IiNmZmYiIHN0b3Atb3BhY2l0eT0iMCIvPjwvbGluZWFyR3JhZGllbnQ+CjxsaW5lYXJHcmFkaWVudCBpZD0iZmRjIiB4MT0iMzUuMDEiIHkxPSI0NC4yMiIgeDI9Ijg0Ljc1IiB5Mj0iNDQuMjIiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj48c3RvcCBzdG9wLWNvbG9yPSIjZmZmIi8+PHN0b3Agb2Zmc2V0PSIuMTY4IiBzdG9wLWNvbG9yPSIjZmZmIi8+PC9saW5lYXJHcmFkaWVudD4KPC9kZWZzPgo8L3N2Zz4=">
<style>
html,body{margin:0;height:100%;background:#0d0f14}
#frame{border:0;width:100vw;height:100vh;display:block}
</style>
</head>
<body>
<iframe id="frame" title="Smart Requirement Manager"></iframe>
<script>
const BLOBS = {
"""

FOOTER = """
};
const ROUTES = {"home": ["home", null], "dashboard": ["dash", "dashboard"], "config": ["dash", "config"], "team": ["dash", "team"], "review": ["review", null], "compliance": ["compliance", "compliance"], "compliance-contributor": ["compliance", "compliance-contributor"], "documents": ["documents", null], "qa": ["qa", null], "risks": ["risks", null], "new": ["create", null]};
function b64utf8(s){return decodeURIComponent(Array.prototype.map.call(atob(s),c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''));}
const frame = document.getElementById('frame');

/* ============ WORKSPACE — project list + background processing ============ */
/* builtOut:true = the project's Dashboard/Allocation/Compliance screens show
   real, hand-authored content for this project specifically. Only "stb2026" qualifies —
   see HANDOVER.md ("Only one project is fully navigable... steer test participants to
   the EMS project for task scenarios"). The other four seeds exist only to illustrate
   the tender list, status badges and background processing — opening one is blocked
   in accueil.html with an explanatory toast instead of silently substituting stb2026's
   content (TA1). Projects created via the wizard (addProject) don't set this flag at
   all — they're intentionally exempt from the block, see addProject below. */
function seedProjects(){
  return [
    // TICKETS-prototype-corrections-consolidated.md §1.2 — the old `health`/`healthNote`
    // ("on track"/"at risk"/"behind") is gone; MyTenders now shows exactly two gauges,
    // Allocation (`allocated`/`total`) and Compliance (`complianceFilled`/`total`,
    // counting internal compliance per §6.1), switching automatically once `allocated`
    // reaches `total`. `done` is kept only as the legacy figure other screens may still
    // read; `allocated`/`complianceFilled` are the new, distinct counts the ticket asked
    // for instead of overloading `done` with two different meanings.
    // TICKET-two-pass-allocation.md — line was "SIG", which contradicted this
    // project's own seed data: its requirements are already distributed across
    // SIG, Mainline and Safety, and only a Turnkey tender distributes across
    // systems like that (a SIG tender is already scoped to SIG). Turnkey
    // also makes pass 1 demonstrable on the one fully-built demo project.
    // SPEC-translation.md §2 — one source language per tender, captured at
    // creation. French here so the demo has a real, reviewable non-English
    // source to show the original/English split against (revue-documentaire's
    // seedDemoSections() carries the matching French originals). The real
    // capture dataset (data.js, gitignored — not this repo's problem to
    // translate) stays English; see TENDER_LANGUAGE's own fallback.
    {id:"stb2026", ref:"STB-2026", name:"Energy Monitoring System", line:"Turnkey", days:23, deadline:1,
     status:"requirement_review", done:10, total:12, allocated:10, complianceFilled:0, updated:"today", primary:true, role:"Project manager", builtOut:true,
     language:"fr"},
    // DEC-044 — the standalone SIG tender, built out so TENDER-PROFILES' "Tender
    // SIG autonome" column is verifiable on a real project. English source
    // (language:"en") exercises the no-translation path, the other half of
    // SPEC-translation.md §2 that STB-2026's French source cannot show.
    // Counts match revue-documentaire.html's seedSigSections(): 12 requirements,
    // 5 of them allocated.
    {id:"rfp114", ref:"RFP-2026-114", name:"Line 4 Resignalling — ETCS L2", line:"SIG", days:9, deadline:1,
     status:"requirement_review", done:4, total:12, allocated:4, complianceFilled:0, updated:"2h ago", role:"Signalling manager", builtOut:true,
     language:"en", system:"Mainline", product:"Mainline Wayside"},
    {id:"ao088", ref:"AO-2026-088", name:"Depot Maintenance Systems", line:"Services", days:41, deadline:1,
     status:"processing", progress:38, procLabel:"Characterising requirements…", updated:"just now", role:"Project manager", builtOut:false},
    {id:"stb133", ref:"STB-2026-133", name:"Regional Fleet Telemetry", line:"Rolling Stock", days:5, deadline:1,
     status:"qa_versioning", done:58, total:63, allocated:63, complianceFilled:58, updated:"yesterday", role:"Contributor", builtOut:false},
    {id:"stb2025", ref:"STB-2025-071", name:"Metro Depot Power Supply", line:"INFRA", days:-12, deadline:1,
     status:"submitted", reqs:88, updated:"Jun 3", role:"Contributor", builtOut:false},
  ];
}
let PROJECTS = seedProjects();
let currentProjectId = "stb2026";
window.getProjects = ()=>PROJECTS;
window.getCurrentProject = ()=>PROJECTS.find(p=>p.id===currentProjectId)||null;

// TICKETS-prototype-batch6.md "Prepare the login for SSO" — there is no login
// screen in this prototype (the app opens straight on My tenders), so there
// is no form to remove. What there WAS: every screen's avatar had "Thibaud
// Breton"/"TB" typed literally into its own markup — six independent copies
// of a hand-entered identity, no single source of truth. This is that source:
// shaped like what an SSO/directory lookup returns (id, name, title, email,
// initials), fetched by every screen the same way getCurrentProject() already
// is. No real SSO integration — prototype-level, per the ticket — but the
// screens and the user model now assume an identity handed to them, not typed.
const CURRENT_USER = {id:"admin", name:"Thibaud Breton", title:"Bid Director", email:"thibaud.breton@company.com", init:"TB"};
window.getCurrentUser = ()=>CURRENT_USER;
// manual-mode project creation routes straight to "review", skipping the
// workspace click that would normally call openProject() — this is the
// direct way to make a just-created project "current" without also
// navigating (openProject both sets it AND routes to the dashboard).
window.setCurrentProject = function(id){ if(PROJECTS.some(p=>p.id===id)) currentProjectId=id; };

/* background processing loop — runs in the shell, survives navigation */
let procTimer=null;
function startProcLoop(){
  if(procTimer) return;
  procTimer=setInterval(()=>{
    let anyActive=false;
    PROJECTS.forEach(p=>{
      if(p.status==="processing"){
        anyActive=true;
        p.progress=(p.progress||0)+ (2+Math.random()*4);
        if(p.progress>=100){
          p.progress=100; p.status="requirement_review";
          p.done=0; p.total=p.total|| (60+Math.floor(Math.random()*40));
          p.updated="just now";
        }else if(p.language && p.language!=="en"){
          // SPEC-translation.md §2/§7 — translation runs after capture, before
          // characterisation, on any tender whose source language isn't English.
          if(p.progress<25) p.procLabel="Capturing requirements…";
          else if(p.progress<50) p.procLabel="Translating requirements…";
          else if(p.progress<75) p.procLabel="Characterising requirements…";
          else p.procLabel="Allocating to contributors…";
        }else{
          if(p.progress<35) p.procLabel="Capturing requirements…";
          else if(p.progress<70) p.procLabel="Characterising requirements…";
          else p.procLabel="Allocating to contributors…";
        }
      }
    });
    if(!anyActive){ clearInterval(procTimer); procTimer=null; }
  }, 700);
}
startProcLoop();

window.addProject = function(meta){
  const id="p"+Date.now().toString(36);
  const manual = meta.mode==="manual";
  const p={ id, ref:meta.ref||("AO-"+id.slice(-4).toUpperCase()), name:meta.name||"Untitled tender",
    line:meta.line||"—", days:meta.days!=null?meta.days:30, deadline:1, updated:"just now",
    role:"Project manager",
    // TICKET-tender-creation-rework.md — casting left the creation wizard
    // entirely (it's ongoing project user management on its own screen now,
    // TICKET-casting-screen-redesign.md), so there's no per-system roster
    // to carry through any more. What creation still collects is the much
    // smaller `pmTeam` — the wizard's own step 4, creator seeded in first.
    // Not consumed by dashboard-et-config.html's redesigned casting screen
    // (that screen owns its own independent PM_TEAM, per this project's
    // no-shared-data-layer convention) — stored here for completeness, same
    // treatment `experts` got before it. Configuration's own "Team &
    // contributors" section already falls back to its own seed list when this is
    // empty, which it always will be now — no change needed there. No
    // `builtOut` flag is set here on purpose — wizard-created projects are
    // exempt from TA1's demo-only block.
    experts: [],
    language: meta.language||"en",  // SPEC-translation.md §2 — captured at creation, one per tender
    // DEC-049 — the product is fixed at creation and is what selects the
    // allocation model downstream (revue-documentaire.html reads it to decide
    // whether the PBS/OBS/ABS keys apply). It was collected by the wizard and
    // then dropped here, so a tender created in the app could never have one.
    product: meta.product||null,
    pmTeam: Array.isArray(meta.pmTeam) ? meta.pmTeam : [] };  // whoever creates the tender owns it
  if(manual){ p.status="requirement_review"; p.done=0; p.total=0; p.allocated=0; p.complianceFilled=0; }
  else { p.status="processing"; p.progress=3; p.procLabel="Capturing requirements…"; p.total=(60+Math.floor(Math.random()*40)); p.allocated=0; p.complianceFilled=0; }
  PROJECTS.unshift(p);
  startProcLoop();
  return id;
};
window.openProject = function(id){
  const p=PROJECTS.find(x=>x.id===id);
  if(!p || p.status==="processing") return;
  currentProjectId=id;
  window.route("dashboard");
};
window.resetDemo = function(){
  PROJECTS = seedProjects();
  currentProjectId="stb2026";
  reviewValidated=false; projectMode='ai'; projectMeta=null;
  aiFeedback.length=0; redactMode='redact'; v22Uploaded=false; customFields={}; tableLayouts={}; partners=seedPartners(); partnerUsage=seedPartnerUsage(); allocProgress={}; strategies=seedStrategies(); strategyUsage=seedStrategyUsage(); risks=seedRisks(); gapDocs=seedGapDocs(); gapStats=seedGapStats();
  reassignRequests.length=0; sharedQuestions={};
  if(procTimer){ clearInterval(procTimer); procTimer=null; }
  startProcLoop();
  window.route("home");
};

// ---- shared cross-screen state ----
let reviewValidated = false;
window.isReviewValidated = ()=>reviewValidated;
window.setReviewValidated = (v)=>{ reviewValidated = !!v; };
// TB5 — has v2.2's gap analysis actually run? The dashboard narrates it as
// already-arrived; this flag lets it gate that on the real trigger (Compliance's
// "Simulate upload — v2.2" button) instead of asserting it as fact on load.
let v22Uploaded = false;
// SPEC-custom-columns.md — column definitions and their values, per tender.
// Held here in the shell, not in the screen: every route reloads the screen's
// iframe, and a column that vanished on the first navigation would demonstrate
// nothing. Values are keyed by requirement id, so they also survive a document
// version resetting a requirement (§8.6) — they are human data, not AI output.
let customFields = {};
// Column widths the user dragged, per tender and per table — a layout
// preference, kept beside the custom columns for the same reason (the screen
// iframe reloads on every route) and cleared by Reset demo like them.
let tableLayouts = {};
window.getTableLayout = (projectId, table)=>{ const k=(projectId||"_")+"::"+table; if(!tableLayouts[k]) tableLayouts[k]={widths:{}}; return tableLayouts[k]; };
window.getCustomFields = (projectId)=>{ const k=projectId||"_"; if(!customFields[k]) customFields[k]={defs:[],values:{},seq:0}; return customFields[k]; };
// SPEC-external-partners.md — systems a project manager adds to a Turnkey
// tender's OBS list (a partner company taking part of the scope). Per tender,
// in the shell like custom columns. The model never predicts them. One seeded
// partner on the Turnkey demo tender so the flow can be shown end to end.
function seedPartners(){ return { stb2026:[{id:"p_voltara", code:"VOLTARA", label:"Voltara Engineering"}] }; }
let partners = seedPartners();
// DEC-093 — a partner can be removed only while no requirement is assigned to it.
// Allocation and Compliance each report how many of their requirements use each
// partner (they own their data; the shell only keeps the counts). Seeded with the
// demo's own use so Settings knows before either screen has been opened.
function seedPartnerUsage(){ return { stb2026:{ p_voltara:{allocation:2, compliance:2} } }; }
let partnerUsage = seedPartnerUsage();
window.reportPartnerUsage = (projectId, screen, counts)=>{ const k=projectId||"_"; const u=partnerUsage[k]=partnerUsage[k]||{};
  (window.getPartners(k)||[]).forEach(p=>{ u[p.id]=u[p.id]||{}; u[p.id][screen]=counts[p.id]||0; }); };
// DEC-098 — Allocation reports its real progress so the dashboard's Allocation
// card can turn Done when every requirement is allocated (Finalize is gone).
let allocProgress = {};
window.reportAllocationProgress = (projectId, p)=>{ allocProgress[projectId||"_"]=p; };
window.getAllocationProgress = (projectId)=>allocProgress[projectId||"_"]||null;
window.getPartnerUsage = (projectId, partnerId)=>{ const u=((partnerUsage[projectId||"_"]||{})[partnerId])||{}; return Math.max(0,...Object.values(u)); };
window.removePartner = (projectId, partnerId)=>{
  if(window.getPartnerUsage(projectId, partnerId)>0) return {error:"used"};
  const list=window.getPartners(projectId), i=list.findIndex(x=>x.id===partnerId);
  if(i<0) return {error:"missing"};
  const [gone]=list.splice(i,1); return {removed:gone};
};
window.getPartners = (projectId)=>{ const k=projectId||"_"; if(!partners[k]) partners[k]=[]; return partners[k]; };
window.addPartner = (projectId, name)=>{
  const list=window.getPartners(projectId), label=String(name||"").trim();
  if(!label) return {error:"empty"};
  if(list.some(x=>x.label.toLowerCase()===label.toLowerCase())) return {error:"duplicate"};
  let code=(label.split(" ").filter(Boolean)[0]||"PARTNER").replace(/[^A-Za-z0-9]/g,"").toUpperCase().slice(0,8)||"PARTNER", base=code, n=2;
  while(list.some(x=>x.code===code)) code=base.slice(0,7)+(n++);
  const entry={id:"p_"+code.toLowerCase(), code, label};
  list.push(entry); return {entry};
};
// SPEC-risks.md §2.1 / DEC-110 — the gap strategies of a tender: what a
// responsible can do about a Not compliant, and the external compliance each
// one produces. Written per tender by the PM; a new tender starts with none.
// The demo tenders carry the usual four so the flow can be shown.
function seedStrategies(){
  const four=()=>[
    {id:"gs_1", name:"Declare NC in offer", ext:"not_compliant"},
    {id:"gs_2", name:"Request adjustment", ext:"pending"},
    {id:"gs_3", name:"Change to reach compliance", ext:"compliant"},
    {id:"gs_4", name:"Keep as a gap", ext:"compliant"},
  ];
  const out={}; ["stb2026","rfp114","ao088","stb133","stb2025"].forEach(k=>{ out[k]=four(); });
  return out;
}
let strategies = seedStrategies();
// Compliance reports, per strategy, how many assignments use it and how many of
// those carry a PM correction of the external compliance (DEC-106). "used" is
// what forbids deleting; used minus corrected is what a change of result moves.
// Seeded with what Compliance reports for the demo data, so Settings knows
// before Compliance has been opened; Compliance overwrites it on each render.
function seedStrategyUsage(){ return {
  stb2026:{gs_1:{used:2,corrected:0}, gs_2:{used:2,corrected:1}, gs_3:{used:2,corrected:0}, gs_4:{used:2,corrected:0}},
  rfp114:{gs_4:{used:1,corrected:0}},
}; }
let strategyUsage = seedStrategyUsage();
window.getStrategies = (projectId)=>{ const k=projectId||"_"; if(!strategies[k]) strategies[k]=[]; return strategies[k]; };
window.reportStrategyUsage = (projectId, counts)=>{ strategyUsage[projectId||"_"]=counts||{}; };
window.getStrategyUsage = (projectId, id)=>{ const u=((strategyUsage[projectId||"_"]||{})[id])||{}; return {used:u.used||0, corrected:u.corrected||0}; };
window.addStrategy = (projectId, name, ext)=>{
  const list=window.getStrategies(projectId), label=String(name||"").trim();
  if(!label) return {error:"empty"};
  if(list.some(x=>x.name.toLowerCase()===label.toLowerCase())) return {error:"duplicate"};
  let n=list.length+1; while(list.some(x=>x.id==="gs_"+n)) n++;
  const entry={id:"gs_"+n, name:label, ext:ext||"pending"};
  list.push(entry); return {entry};
};
window.renameStrategy = (projectId, id, name)=>{
  const list=window.getStrategies(projectId), label=String(name||"").trim(), x=list.find(e=>e.id===id);
  if(!x) return {error:"missing"};
  if(!label) return {error:"empty"};
  if(list.some(e=>e.id!==id && e.name.toLowerCase()===label.toLowerCase())) return {error:"duplicate"};
  x.name=label; return {entry:x};
};
window.setStrategyResult = (projectId, id, ext)=>{
  const x=window.getStrategies(projectId).find(e=>e.id===id); if(!x) return {error:"missing"};
  x.ext=ext; return {entry:x};
};
// SPEC-risks.md §2.1 — a strategy in use cannot be deleted, only renamed.
window.removeStrategy = (projectId, id)=>{
  if(window.getStrategyUsage(projectId, id).used>0) return {error:"used"};
  const list=window.getStrategies(projectId), i=list.findIndex(e=>e.id===id);
  if(i<0) return {error:"missing"};
  const [gone]=list.splice(i,1); return {removed:gone};
};
// SPEC-risks.md §4-§5 — the tender's risk register, and for each Not compliant
// assignment its gap documentation: the strategy picked, the risks linked, and a
// PM correction of the derived external compliance (DEC-106). Keyed
// "<requirement id>#<system>", held here so the Risks page and Compliance read
// the same links. Risks are created from Compliance and reused across requirements.
// DEC-112 — demo register. The three "Risk accepted" texts of the old
// declaration model (SRM-00005, SRM-00007, L4-0010) became risks written to the
// three-sentence template; the other Not compliant of the Turnkey demo share
// risks to show reuse (SRM-00026/-00056, SRM-00038/-00068), with different
// strategies on the same risk, one closed risk, one PM correction, and a few
// gaps left undocumented so the flags show (SRM-00086, SRM-00098).
function seedRisks(){
  const R=(id,weight,activities,createdBy,createdAt,desc,extra)=>Object.assign({id,desc,weight,status:"open",activities,createdBy,createdAt,comments:[]},extra||{});
  return {
    stb2026:[
      R("RSK-00001","high",["sig"],"Louis Renaud","Jul 14","There is a risk that third-party tools load the telemetry API beyond its rate limits.\\nThe risk is caused by the current gateway, sized for our own dashboards only.\\nThe direct impact of the risk will be a gateway rework, priced as a contract option.",
        {comments:[{by:"Louis Renaud",date:"Jul 14",text:"Load test figures attached to SRM-00007's answer."},{by:"Thibaud Breton",date:"Jul 15",text:"Agreed to keep it as a gap — the option is in the price schedule."}]}),
      R("RSK-00002","medium",["sig"],"Louis Renaud","Jul 13","There is a risk that the issuer's escalation matrix cannot be wired into our alerting as delivered.\\nThe risk is caused by the matrix being provided by the issuer only at contract award.\\nThe direct impact of the risk will be a late integration of escalation rules during delivery.",
        {comments:[{by:"Louis Renaud",date:"Jul 13",text:"Asked for an adjustment — see QA-05."}]}),
      R("RSK-00003","high",["sen"],"Paolo Ferri","Jul 16","There is a risk that the secondary depot cluster stays below 99.7% business-hours availability.\\nThe risk is caused by older hardware on that cluster (99.4% measured last quarter).\\nThe direct impact of the risk will be availability penalties on the depot scope."),
      R("RSK-00004","medium",["trk"],"Amina Cherif","Jul 17","There is a risk that regional aggregation reports are logged later than 2 seconds after the event.\\nThe risk is caused by the batch interval of the aggregation service.\\nThe direct impact of the risk will be a latency deviation on every regional report."),
      R("RSK-00005","low",["sen"],"Karim Benali","Jul 18","There is a risk that the gateway firmware cannot encrypt dashboard layouts within 2 seconds.\\nThe risk is caused by the encryption library of the current firmware release.\\nThe direct impact of the risk will be a firmware release outside the bid scope."),
      R("RSK-00006","negligible",["sig"],"Sophie Lang","Jul 10","There is a risk that the escalation matrix contradicts the alert thresholds.\\nThe risk is caused by two sources for the same thresholds.\\nThe direct impact of the risk will be rework of the alert configuration.",
        {status:"closed", comments:[{by:"Sophie Lang",date:"Jul 13",text:"Closed this risk."},{by:"Sophie Lang",date:"Jul 13",text:"The issuer confirmed in QA-05 that the matrix follows the configured thresholds."}]}),
    ],
    rfp114:[
      R("RSK-00001","high",["sig"],"Louis Renaud","Jul 16","There is a risk that a route is released too late when the last track section's detection is lost.\\nThe risk is caused by the standard product releasing routes on the nominal configuration only.\\nThe direct impact of the risk will be a product change for the degraded mode, priced as a contract option."),
    ],
  };
}
function seedGapDocs(){
  const D=(reqId,typology,sec,text,managerName,strategy,risks,override)=>[reqId+"#"+typology,{strategy,risks,override:override||null,meta:{reqId,typology,sec,text,managerName}}];
  return {
    stb2026:Object.fromEntries([
      D("SRM-00005","sig","2. Functional requirements","The system SHALL generate an alert when a site's consumption exceeds the configured threshold for more than 5 consecutive minutes, and notify the operator according to the escalation matrix.","Louis Renaud","gs_2",["RSK-00002","RSK-00006"]),
      D("SRM-00007","sig","2. Functional requirements","The system SHALL expose site telemetry to third-party tools through a documented REST API.","Louis Renaud","gs_4",["RSK-00001"]),
      D("SRM-00011","sen","3. Performance requirements","The system SHALL ensure 99.7% availability during business hours, measured monthly, excluding planned maintenance windows.","Paolo Ferri","gs_1",["RSK-00003"]),
      D("SRM-00026","trk","4. Security requirements","The platform SHALL log regional aggregation reports within 2 seconds of the triggering event.","Amina Cherif","gs_3",["RSK-00004"]),
      D("SRM-00056","trk","4. Security requirements","The platform SHALL log regional aggregation reports within 2 seconds of the triggering event.","Amina Cherif","gs_4",["RSK-00004"]),
      D("SRM-00086","trk","4. Security requirements","The platform SHALL log regional aggregation reports within 2 seconds of the triggering event.","Amina Cherif","gs_3",[]),
      D("SRM-00038","sen","4. Security requirements","The gateway firmware SHALL encrypt dashboard widget layouts within 2 seconds of the triggering event.","Paolo Ferri","gs_1",["RSK-00005"]),
      D("SRM-00068","sen","4. Security requirements","The gateway firmware SHALL encrypt dashboard widget layouts within 2 seconds of the triggering event.","Paolo Ferri","gs_2",["RSK-00005"],
        {ext:"not_compliant", reason:"The client refused any adjustment on the encryption scope in the Jul 20 clarification meeting.", by:"Thibaud Breton", date:"Jul 20"}),
    ]),
    rfp114:Object.fromEntries([
      D("L4-0010","sig","3. Wayside and interlocking","Each interlocking SHALL guarantee that no conflicting route can be set simultaneously, and SHALL release a route only once the train has been confirmed clear of the last track section.","Louis Renaud","gs_4",["RSK-00001"]),
    ]),
  };
}
let risks = seedRisks();
let gapDocs = seedGapDocs();
window.getRisks = (projectId)=>{ const k=projectId||"_"; if(!risks[k]) risks[k]=[]; return risks[k]; };
window.addRisk = (projectId, r)=>{
  const list=window.getRisks(projectId), desc=String((r&&r.desc)||"").trim();
  if(!desc) return {error:"empty"};
  const n=list.reduce((m,x)=>Math.max(m, parseInt(String(x.id).slice(4),10)||0),0)+1;
  const entry={id:"RSK-"+String(n).padStart(5,"0"), desc, weight:r.weight||"medium", status:"open",
    activities:r.activity?[r.activity]:[], createdBy:r.createdBy||null, createdAt:r.createdAt||"Today", comments:[]};
  list.push(entry); return {entry};
};
window.updateRisk = (projectId, id, patch)=>{ const x=window.getRisks(projectId).find(e=>e.id===id); if(!x) return {error:"missing"}; Object.assign(x, patch||{}); return {entry:x}; };
window.getGapDocs = (projectId)=>{ const k=projectId||"_"; if(!gapDocs[k]) gapDocs[k]={}; return gapDocs[k]; };
window.getGapDoc = (projectId, key)=>window.getGapDocs(projectId)[key]||null;
window.setGapDoc = (projectId, key, patch)=>{
  const all=window.getGapDocs(projectId);
  const d=all[key]=Object.assign(all[key]||{strategy:null, risks:[], override:null}, patch||{});
  // a risk linked from another activity lists that activity too (§5)
  if(d.meta && d.meta.typology) (d.risks||[]).forEach(id=>{ const x=window.getRisks(projectId).find(e=>e.id===id); if(x && !x.activities.includes(d.meta.typology)) x.activities.push(d.meta.typology); });
  return d;
};
window.clearGapDoc = (projectId, key)=>{ delete window.getGapDocs(projectId)[key]; };
// SPEC-risks.md §9 — Compliance reports its totals (assignments, verdicts, Not
// compliant documented, external) each time it renders; the dashboard reads them.
// Same reason: the dashboard's risk figures on first load, as Compliance
// computes them for the demo data (it overwrites them on each render).
function seedGapStats(){ return {
  stb2026:{reqs:104, assignments:124, assigned:100, answered:58, compliant:49, nc:9, ncLogged:7, byStrategy:{gs_1:2,gs_2:2,gs_3:2,gs_4:2}, noStrategy:1, ext:{compliant:43,not_compliant:2,pending:1,none:58}},
  rfp114:{reqs:12, assignments:12, assigned:10, answered:5, compliant:4, nc:1, ncLogged:1, byStrategy:{gs_4:1}, noStrategy:0, ext:{compliant:5,not_compliant:0,pending:0,none:7}},
}; }
let gapStats = seedGapStats();
window.reportGapStats = (projectId, st)=>{ gapStats[projectId||"_"]=st; };
window.getGapStats = (projectId)=>gapStats[projectId||"_"]||null;
window.addRiskComment = (projectId, id, c)=>{ const x=window.getRisks(projectId).find(e=>e.id===id); if(!x) return {error:"missing"};
  const entry={by:c.by||"—", date:c.date||"Today", text:String(c.text||"").trim()}; if(!entry.text) return {error:"empty"};
  x.comments.push(entry); return {entry}; };
// SPEC-risks.md §6.4 — merge: every link moves to the kept risk, the others are
// deleted, and the kept risk's comments carry the trace.
window.mergeRisks = (projectId, keepId, ids, by)=>{
  const list=window.getRisks(projectId), keep=list.find(e=>e.id===keepId); if(!keep) return {error:"missing"};
  const gone=ids.filter(id=>id!==keepId && list.some(e=>e.id===id)); if(!gone.length) return {error:"nothing"};
  let moved=0;
  Object.values(window.getGapDocs(projectId)).forEach(d=>{
    if(!(d.risks||[]).some(id=>gone.includes(id))) return;
    moved+=d.risks.filter(id=>gone.includes(id)).length;
    const next=[]; d.risks.forEach(id=>{ const t=gone.includes(id)?keepId:id; if(!next.includes(t)) next.push(t); }); d.risks=next;
  });
  gone.forEach(id=>{ const x=list.find(e=>e.id===id); (x.activities||[]).forEach(a=>{ if(!keep.activities.includes(a)) keep.activities.push(a); }); });
  for(let i=list.length-1;i>=0;i--) if(gone.includes(list[i].id)) list.splice(i,1);
  keep.comments.push({by:by||"—", date:"Today", text:`Merged ${gone.join(", ")} into this risk — ${moved} link${moved===1?"":"s"} moved here.`, system:true});
  return {kept:keep, gone, moved};
};
// One-shot hand-off between screens: "open this risk", "filter Compliance on it".
// The target screen takes it on load; the iframe reloads on every route.
let screenFocus = {};
window.setScreenFocus = (screen, payload)=>{ screenFocus[screen]=payload; };
window.takeScreenFocus = (screen)=>{ const f=screenFocus[screen]||null; delete screenFocus[screen]; return f; };
window.isV22Uploaded = ()=>v22Uploaded;
window.setV22Uploaded = (v)=>{ v22Uploaded = !!v; };
let projectMode = 'ai';
window.getProjectMode = ()=>projectMode;
window.setProjectMode = (m)=>{ projectMode = m || 'ai'; };
let projectMeta = null;
window.getProjectMeta = ()=>projectMeta;
window.setProjectMeta = (m)=>{ projectMeta = m; };
// AI feedback — accumulated across screens, future-training only
const aiFeedback = [];
window.pushAIFeedback = (f)=>{ aiFeedback.push(Object.assign({at:Date.now()},f)); };
window.getAIFeedback = ()=>aiFeedback;
// B10 — reassignment requests, shared across screens so a request raised by a
// contributor (compliance.html) is visible to the project manager's approval
// queue (revue-documentaire.html) and vice versa; each screen owns its own
// requirement data, this is only the cross-screen mailbox.
const reassignRequests = [];
window.pushReassignRequest = function(req){
  req.id = req.id || ('RR-'+(reassignRequests.length+1));
  req.at = req.at || 'Today';
  req.requestStatus = 'pending';
  reassignRequests.push(req);
  return req;
};
window.getReassignRequests = ()=>reassignRequests;
// DEC-088 — a question to the client raised on Compliance goes into the tender's
// Q&A register as a draft, for the project manager to review, merge and send in a
// batch. The shell is the mailbox between the two screens (same idea as the
// reassignment requests above); ids are given here so both screens agree.
let sharedQuestions = {};
window.pushQuestion = function(projectId, q){
  const k=projectId||"_", list=sharedQuestions[k]=sharedQuestions[k]||[];
  q.id = q.id || ('QA-'+(50+list.length+1));
  list.push(q); return q;
};
window.getQuestions = (projectId)=>sharedQuestions[projectId||"_"]||[];
window.withdrawQuestion = function(projectId, id){
  const l=sharedQuestions[projectId||"_"]; if(!l) return;
  const i=l.findIndex(x=>x.id===id); if(i>=0) l.splice(i,1);
};
window.updateReassignRequest = function(id, patch){
  const r = reassignRequests.find(x=>x.id===id);
  if(r) Object.assign(r, patch);
  return r;
};
let redactMode = 'redact';
window.getRedactMode = ()=>redactMode;
window.setRedactMode = (m)=>{ redactMode = m || 'redact'; };
let theme = 'light';
window.getTheme = ()=>theme;
window.setTheme = (t)=>{ theme = (t==='light')?'light':'dark';
  try{ const fr=document.getElementById('frame'); if(fr&&fr.contentDocument) fr.contentDocument.documentElement.setAttribute('data-theme',theme); }catch(e){}
};
let _sub = null;
function load(routeKey){
  const r = ROUTES[routeKey] || ROUTES['dashboard'];
  _sub = r[1];
  frame.onload = function(){
    try{
      const cw = frame.contentWindow;
      if(_sub === 'config' && cw.showConfig) cw.showConfig(true);
      else if(_sub === 'dashboard' && cw.showConfig) cw.showConfig(false);
      else if(_sub === 'team' && cw.showScreen) cw.showScreen('team');
      else if(_sub === 'compliance' && cw.setScreen) cw.setScreen(2);
      else if(_sub === 'compliance-contributor' && cw.setScreen){ cw.setScreen(2); if(cw.setDemoContributorView) cw.setDemoContributorView(); }
    }catch(e){}
  };
  frame.srcdoc = b64utf8(BLOBS[r[0]]);
}
// called from inside the iframe (same-origin srcdoc)
window.route = function(key){
  if(location.hash.slice(1) === key){ load(key); }   // same route: force reload
  else location.hash = key;                            // triggers hashchange -> load
};
const URLMAP = {
  'accueil.html':'home',
  'revue-documentaire.html':'review',
  'compliance.html':'compliance',
  'compliance.html#contributor':'compliance-contributor',
  'documents.html':'documents',
  'qa.html':'qa',
  'risks.html':'risks',
  'dashboard-et-config.html':'dashboard',
  'dashboard-et-config.html#config':'config',
  'creation-projet.html':'new'
};
window.routeUrl = function(u){ window.route(URLMAP[u] || 'dashboard'); };
// moderator shortcut: Ctrl+Shift+R resets the demo
window.addEventListener('keydown', (e)=>{
  if(e.ctrlKey && e.shiftKey && (e.key==='R'||e.key==='r')){ e.preventDefault();
    if(confirm('Reset the demo to its initial state?')) window.resetDemo();
  }
});
window.addEventListener('hashchange', ()=>load(location.hash.slice(1) || 'home'));
load(location.hash.slice(1) || 'home');
</script>
</body>
</html>
"""

def main():
    with open(SHARED_JS_FILE, encoding="utf-8") as f:
        shared_js = f.read()
    with open(SHARED_CSS_FILE, encoding="utf-8") as f:
        shared_css = f.read()

    # data.js is optional — nobody may have run import_capture.py yet, and the
    # prototype must still build (falling back to buildBigData(n)) if so.
    capture_js = ""
    if Path(DATA_FILE).is_file():
        with open(DATA_FILE, encoding="utf-8") as f:
            capture_js = f.read()
    else:
        print(f"Note: {DATA_FILE} not found — revue-documentaire.html will use its synthetic seed data.")
    with open(KEYS_FILE, encoding="utf-8") as f:
        keys_js = f.read()

    # Antarctica (the brand title face) is licensed and not versioned. The
    # screens declare it with a url() fallback so dropping the files under
    # fonts/ needs no code change — but while they are missing that url() is
    # a 404 on every screen load, which reads as "broken" in any devtools.
    # Same treatment as data.js: keep the reference only when the files exist.
    antarctica_present = all(Path(f"fonts/Antarctica-{w}.woff2").is_file() for w in ("Regular", "Bold"))
    if not antarctica_present:
        print("Note: fonts/Antarctica-*.woff2 not found — titles fall back to Noto Sans (see fonts/README.md).")

    blob_lines = []
    for key, filename in SOURCES:
        with open(filename, encoding="utf-8") as f:
            html = f.read()
        if INCLUDE_MARKER in html:
            html = html.replace(INCLUDE_MARKER, shared_js)
        if DATA_INCLUDE_MARKER in html:
            html = html.replace(DATA_INCLUDE_MARKER, capture_js)
            html = html.replace(KEYS_INCLUDE_MARKER, keys_js)
        if not antarctica_present:  # every screen declares the face, not just the one with data.js
            html = html.replace(',url("fonts/Antarctica-Regular.woff2") format("woff2")', "")
            html = html.replace(',url("fonts/Antarctica-Bold.woff2") format("woff2")', "")
        if CSS_INCLUDE_MARKER in html:
            html = html.replace(CSS_INCLUDE_MARKER, shared_css)
        b64 = base64.b64encode(html.encode("utf-8")).decode("ascii")
        blob_lines.append(f'{key}:"{b64}",')

    body = HEADER + "\n".join(blob_lines) + FOOTER
    for target in (OUTPUT, PAGES_OUTPUT):
        with open(target, "w", encoding="utf-8") as f:
            f.write(body)
    print(f"Wrote {OUTPUT} and {PAGES_OUTPUT} ({len(body)} bytes) from {len(SOURCES)} sources.")

if __name__ == "__main__":
    main()
