#!/usr/bin/env python3
"""
build_keys.py — turns the "PBS OBS ABS Keys" workbook into keys.js.

The workbook (v260720) is three sheets, one per breakdown axis, each a shared
reference list with one column per product — URBAN, Mainline Wayside, Mainline
Onboard — holding an "x" where the entry applies. That is DEC-047 made concrete:
the product selects the model, and the model is a subset of a common vocabulary.

  PBS   a three-level tree of product elements (2 Signalling > 2.1 IXL >
        2.1.2 Point Machine…). A few rows were added by hand without an id.
  ABS   sixteen flat activity categories.
  OBS   job titles, grouped UNDER the ABS categories (rows whose column E says
        "ABS" are group headers), each with skill / SoA / job codes.

Loaded as-is, per DEC-061: duplicates, id-less rows and x/X casing are the
file's to fix, not ours, and the two side lists on the ABS sheet are ignored.

Usage:  python3 build_keys.py [path/to/workbook.xlsx]
Writes: keys.js (committed — the workbook itself is not).
"""
import json, re, sys
try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is required: pip3 install openpyxl")

SRC = sys.argv[1] if len(sys.argv) > 1 else "/Users/thibaudbreton/Downloads/PBSOBSABS Keys v260720.xlsx"
OUT = "keys.js"
VERSION = re.search(r"v(\d{6})", SRC)
VERSION = VERSION.group(0) if VERSION else "unknown"

PRODUCTS = ["urban", "mainline-wayside", "mainline-onboard"]
flag = lambda v: isinstance(v, str) and v.strip().lower() == "x"
clean = lambda v: re.sub(r"\s+", " ", str(v)).strip() if v is not None else ""

wb = openpyxl.load_workbook(SRC, data_only=True)

# ---- PBS ---------------------------------------------------------------
rows = [r for r in wb["PBS"].iter_rows(min_row=2, values_only=True) if clean(r[5])]
pbs = []
anon = 0
family = None          # current level-2 element id
sub = None             # current level-3 element id
for i, r in enumerate(rows):
    name = clean(r[5]); eid = clean(r[0]); parent = clean(r[1]); level = r[2]
    if eid:
        level = int(level)
        if level == 2: family, sub = eid, None
        elif level == 3: sub = eid
    else:
        # Hand-added row with no id. It is a level-4 child of the current
        # level-3 element only when it sits INSIDE that element's run of
        # children (the next id'd row still has the same parent); otherwise it
        # is a level-3 entry of the current family, which is where "Train
        # Detection" and its four siblings belong rather than under whatever
        # sub-system happened to precede them on the sheet.
        nxt = next((x for x in rows[i+1:] if clean(x[0])), None)
        inside = nxt is not None and clean(nxt[1]) == sub and sub is not None
        anon += 1; eid = f"x{anon}"
        parent, level = (sub, 4) if inside else (family, 3)
    products = [p for p, col in zip(PRODUCTS, r[6:9]) if flag(col)]
    pbs.append({"id": eid, "parent": parent or None, "level": level,
                "name": name, "label": clean(r[9]) or None, "products": products})

# ---- ABS ---------------------------------------------------------------
abs_ = []
for r in wb["ABS (2)"].iter_rows(min_row=2, values_only=True):
    cat = clean(r[0])
    if not cat:
        continue
    abs_.append({"id": re.sub(r"[^a-z0-9]+", "-", cat.lower()).strip("-"), "label": cat,
                 "note": clean(r[4]) or None,
                 "products": [p for p, col in zip(PRODUCTS, r[1:4]) if flag(col)]})
abs_by_label = {a["label"].lower(): a["id"] for a in abs_}
abs_by_label["standards / certifications"] = abs_by_label.get("standards")

# ---- OBS ---------------------------------------------------------------
obs = []
current_abs = None
for r in wb["OBS (2)"].iter_rows(min_row=2, values_only=True):
    title = clean(r[0])
    if not title:
        continue
    if clean(r[4]) == "ABS":
        current_abs = abs_by_label.get(title.lower())
        continue
    obs.append({"id": f"obs{len(obs)+1}", "title": title, "abs": current_abs,
                "skills": clean(r[1]) or None, "soa": clean(r[2]) or None, "code": clean(r[3]) or None,
                "products": [p for p, col in zip(PRODUCTS, r[5:8]) if flag(col)]})

data = {"version": VERSION, "products": PRODUCTS, "pbs": pbs, "abs": abs_, "obs": obs}
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* Generated by build_keys.py from the PBS/OBS/ABS Keys workbook (%s). Do not edit by hand. */\n" % VERSION)
    f.write("window.SRM_KEYS=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")

def n(items, p): return sum(1 for i in items if p in i["products"])
print(f"{OUT}: PBS {len(pbs)} ({', '.join(f'{p} {n(pbs,p)}' for p in PRODUCTS)}) · "
      f"ABS {len(abs_)} · OBS {len(obs)} ({', '.join(f'{p} {n(obs,p)}' for p in PRODUCTS)}) · orphans without abs: {sum(1 for o in obs if not o['abs'])}")
